version: '3.2'

services:
  app:
    build: .
    container_name: wallet_service_container
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/wallet_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-dev}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-devpass}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    container_name: wallet_service_db_container
    restart: always
    environment:
      PGPORT: 5432
      POSTGRES_DB: wallet_db
      POSTGRES_USER: ${DB_USERNAME:-dev}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-devpass}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    volumes:
      - ./data/postgres:/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: 