spring:
  application:
    name: wallet-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/wallet_db}
    username: ${DB_USERNAME:dev}
    password: ${DB_PASSWORD:devpass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: ${SHOW_SQL:false}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    com.wallet: ${LOG_LEVEL:INFO}
    org.hibernate.SQL: ${SHOW_SQL:false}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html 